apiVersion: redhatcop.redhat.io/v1alpha1
kind: ResourceLocker
metadata:
  name: appmanager-resource-locker
  namespace: resource-locker-operator
spec:
  patches:
  - id: aiopsedge-operator-controller-manager-locker
    patchTemplate: |
      spec:
        replicas: {{.Values.res.aiopsedgeOperator.replicas}}
    patchType: application/strategic-merge-patch+json
    targetObjectRef:
      apiVersion: apps/v1
      kind: Deployment
      name: aiopsedge-operator-controller-manager
      namespace: {{.Values.spec.cp4waiops_namespace}}
  - id: aiopsanalyticsorchestrator-locker
    patchTemplate: |
      spec:
        pullSecrets:
        - ibm-entitlement-key
    patchType: application/merge-patch+json
    targetObjectRef:
      apiVersion: ai.ir.aiops.ibm.com/v1beta1
      kind: AIOpsAnalyticsOrchestrator
      name: aiops
      namespace: {{.Values.spec.cp4waiops_namespace}}
  - id: aiops-topology-service-account-locker
    patchTemplate: |
      imagePullSecrets:
      - name: ibm-entitlement-key
      metadata:
        labels:
          managedByUser: "true"
    patchType: application/strategic-merge-patch+json
    targetObjectRef:
      apiVersion: v1
      kind: ServiceAccount
      name: aiops-topology-service-account
      namespace: {{.Values.spec.cp4waiops_namespace}}
  - id: aiops-ir-lifecycle-locker
    patchTemplate: |
      spec:
        flink:
          jobManager: 
            replicas: {{.Values.res.irflink.jobmanager.replicas}}
            template:
              pod:
                spec:
                  containers:
                  - name: jobmanager
                    resources:
                      limits:
                        cpu: "{{.Values.res.irflink.jobmanager.jobmanager.limits.cpu}}"
                        memory: "{{.Values.res.irflink.jobmanager.jobmanager.limits.memory}}"
                      requests:
                        cpu: "{{.Values.res.irflink.jobmanager.jobmanager.requests.cpu}}"
                        memory: "{{.Values.res.irflink.jobmanager.jobmanager.requests.memory}}"
                  - name: tls-proxy
                    resources:
                      limits:
                        cpu: "{{.Values.res.irflink.jobmanager.tlsproxy.limits.cpu}}"
                        memory: "{{.Values.res.irflink.jobmanager.tlsproxy.limits.memory}}"
                      requests:
                        cpu: "{{.Values.res.irflink.jobmanager.tlsproxy.requests.cpu}}"
                        memory: "{{.Values.res.irflink.jobmanager.tlsproxy.requests.memory}}"
          properties:
             jobmanager.memory.process.size: "{{.Values.res.irflink.jobmanager.processSize}}"
             taskmanager.memory.process.size: "{{.Values.res.irflink.taskmanager.processSize}}"
          taskManager:
            replicas: {{.Values.res.irflink.taskmanager.replicas}}
            template:
              pod:
                spec:
                  containers:
                  - name: taskmanager
                    resources:
                      limits:
                        cpu: "{{.Values.res.irflink.taskmanager.taskmanager.limits.cpu}}"
                        memory: "{{.Values.res.irflink.taskmanager.taskmanager.limits.memory}}"
                      requests:
                        cpu: "{{.Values.res.irflink.taskmanager.taskmanager.requests.cpu}}"
                        memory: "{{.Values.res.irflink.taskmanager.taskmanager.requests.memory}}"
    patchType: application/merge-patch+json
    targetObjectRef:
      apiVersion: eventprocessing.automation.ibm.com/v1beta1
      kind: EventProcessor
      name: aiops-ir-lifecycle
      namespace: {{.Values.spec.cp4waiops_namespace}}
  serviceAccountRef:
    name: resource-locker-operator-controller-manager
