apiVersion: redhatcop.redhat.io/v1alpha1
kind: ResourceLocker
metadata:
  name: iaf-resource-locker
  namespace: resource-locker-operator
spec:
  patches:
  - id: nginx-replicas
    patchTemplate: |
      spec:
        replicas: 1
    patchType: application/strategic-merge-patch+json
    targetObjectRef:
      apiVersion: apps/v1
      kind: Deployment
      name: ibm-nginx
      namespace: {{.Values.spec.cp4waiops_namespace}}
  - id: usermgmt-replicas
    patchTemplate: |
      spec:
        replicas: 1
    patchType: application/strategic-merge-patch+json
    targetObjectRef:
      apiVersion: apps/v1
      kind: Deployment
      name: usermgmt
      namespace: {{.Values.spec.cp4waiops_namespace}}
  - id: zen-core-replicas
    patchTemplate: |
      spec:
        replicas: 1
    patchType: application/strategic-merge-patch+json
    targetObjectRef:
      apiVersion: apps/v1
      kind: Deployment
      name: zen-core
      namespace: {{.Values.spec.cp4waiops_namespace}}
  - id: zen-core-api-replicas
    patchTemplate: |
      spec:
        replicas: 1
    patchType: application/strategic-merge-patch+json
    targetObjectRef:
      apiVersion: apps/v1
      kind: Deployment
      name: zen-core-api
      namespace: {{.Values.spec.cp4waiops_namespace}}
  - id: automationbase-custom-profile
    patchTemplate: |
      spec:
        elasticsearch:
          nodegroupspecs:
            - config:
              - key: node.master
                value: "true"
              - key: node.data
                value: "true"
              name: aiops
              replicas: 1
              storage:
                class: rook-cephfs
              template:
                pod:
                  spec:
                    containers:
                    - env:
                      - name: ES_JAVA_OPTS
                        value: -Xms512M -Xmx512M
                      name: elasticsearch
                      resources:
                        limits:
                          cpu: 500m
                          memory: 1Gi
                        requests:
                          cpu: 250m
                          memory: 1Gi
                    - name: tls-proxy
                      resources:
                        limits:
                          cpu: 500m
                          memory: 200Mi
                        requests:
                          cpu: 100m
                          memory: 100Mi
        kafka:
          entityOperator:
            tlsSidecar:
              resources:
                limits:
                  cpu: 500m
                  memory: 128Mi
                requests:
                  cpu: 100m
                  memory: 64Mi
            topicOperator:
              resources:
                limits:
                  cpu: 500m
                  memory: 256Mi
                requests:
                  cpu: 100m
                  memory: 256Mi
            userOperator:
              resources:
                limits:
                  cpu: 500m
                  memory: 256Mi
                requests:
                  cpu: 100m
                  memory: 256Mi
          kafka:
            config:
              default.replication.factor: 1
              min.insync.replicas: 1
            replicas: 1
            resources:
              limits:
                cpu: 500m
                memory: 1Gi
              requests:
                cpu: 250m
                memory: 500Mi
            storage:
              class: rook-cephfs
              size: 30Gi
          zookeeper:
            replicas: 1
            resources:
              limits:
                cpu: 1000m
                memory: 256Mi
              requests:
                cpu: 50m
                memory: 256Mi
            storage:
              class: rook-cephfs
    patchType: application/merge-patch+json
    targetObjectRef:
      apiVersion: base.automation.ibm.com/v1beta1
      kind: AutomationBase
      name: automationbase-sample
      namespace: {{.Values.spec.cp4waiops_namespace}}
  - id: cp4waiops-eventprocessor-custom-profile
    patchTemplate: |
      spec:
        flink:
          jobManager: 
            replicas: 1
            template:
              pod:
                spec:
                  containers:
                  - name: jobmanager
                    resources:
                      limits:
                        cpu: 750m
                        memory: 768Mi
                      requests:
                        cpu: 100m
                        memory: 768Mi
                  - name: tls-proxy
                    resources:
                      limits:
                        cpu: 500m
                        memory: 512Mi
                      requests:
                        cpu: 100m
                        memory: 256Mi
          properties:
             jobmanager.memory.heap.size: 256mb
             jobmanager.memory.jvm-metaspace.size: 64mb
             taskmanager.memory.heap.size: 800mb
             taskmanager.memory.managed.size: 102mb
             taskmanager.numberOfTaskSlots: "8"
          taskManager:
            replicas: 1
            template:
              pod:
                spec:
                  containers:
                  - name: taskmanager
                    resources:
                      limits:
                        cpu: "1"
                        memory: 1200Mi
                      requests:
                        cpu: 500m
                        memory: 1200Mi
    patchType: application/merge-patch+json
    targetObjectRef:
      apiVersion: eventprocessing.automation.ibm.com/v1beta1
      kind: EventProcessor
      name: cp4waiops-eventprocessor
      namespace: {{.Values.spec.cp4waiops_namespace}}
  serviceAccountRef:
    name: resource-locker-operator-controller-manager
