---
###################################
# Common Configuration
###################################
spec:

  ## cp4waiops_namespace is the project (namespace) that you want to create the AI Manager instance in.
  ## You must create a custom project (namespace) and not use the default, kube-system,
  ## kube-public, openshift-node, openshift-infra, or openshift projects (namespaces). 
  ## This is because AI Manager uses Security Context Constraints (SCC), 
  ## and SCCs cannot be assigned to pods created in one of the default OpenShift projects (namespaces).
  ##
  cp4waiops_namespace: cp4waiops

  ## AI Manager catalog source image
  ##
  imageCatalog: icr.io/cpopen/ibm-operator-catalog:latest

  ## A channel defines a stream of updates for an Operator and is used to roll out updates for subscribers. 
  ## For example, if you want to install CP4WAIOps 3.2, the channel should be v3.2
  ##
  channel: v3.2

  ## size is the size that you require for your AI Manager installation. It can be small or large.
  ## More information: https://www.ibm.com/docs/en/cloud-paks/cloud-pak-watson-aiops/3.2.0?topic=requirements-ai-manager
  size: small

  ## dockerUsername is the usrname of IBM® Entitled Registry.
  ## It is used to create a docker-registry secret to enable your deployment to pull the AI Manager images 
  ## from the IBM® Entitled Registry.
  ## Default is cp
  dockerUsername: cp

  ## Obtain the entitlement key that is assigned to your IBMid. 
  ## Log in to MyIBM Container Software Library: https://myibm.ibm.com/products-services/containerlibrary
  ## Opens in a new tab with the IBMid and password details 
  ## that are associated with the entitled software.
  ## 
  dockerPassword: REPLACE_IT

  ## storageClass is the storage class that you want to use. 
  ## If the storage provider for your deployment is Red Hat OpenShift Data Foundation, 
  ## previously called Red Hat OpenShift Container Storage, then set this to ocs-storagecluster-cephfs
  ##
  storageClass: rook-cephfs

  ## If the storage provider for your deployment is Red Hat OpenShift Data Foundation, 
  ## previously called Red Hat OpenShift Container Storage, then set this to ocs-storagecluster-ceph-rbd
  storageClassLargeBlock: rook-cephfs

  ## installationName is the Installation CR name for CP4WAIOps
  installationName: aiops-installation

###################################
# Custom Profile Configuration
###################################

res:
  cassandra:
    replicas: 1
    limits:
      cpu: 600m
      memory: 1500Mi
    requests:
      cpu: 200m
      memory: 1500Mi
    heap:
      size: 600M
      newSize: 150M

  couchdbcluster:
    db:
      limits:
        cpu: "700m"
        memory: "768Mi"
      requests:
        cpu: "250m"
        memory: "768Mi"
    search:
      limits:
        cpu: "500m"
        memory: "250Mi"
      requests:
        cpu: "250m"
        memory: "250Mi"
    mgmt:
      limits:
        cpu: "500m"
        memory: "128Mi"
      requests:
        cpu: "250m"
        memory: "64Mi"

  redis:
    member:
      db:
        limits:
          cpu: "500m"
          memory: 512Mi
        requests:
          cpu: "60m"
          memory: 256Mi
      mgmt:
        limits:
          cpu: "500m"
          memory: 150Mi
        requests:
          cpu: "60m"
          memory: 100Mi
      proxy:
        limits:
          cpu: "500m"
          memory: 150Mi
        requests:
          cpu: "60m"
          memory: 100Mi
      proxylog:
        limits:
          cpu: "500m"
          memory: 150Mi
        requests:
          cpu: "60m"
          memory: 100Mi
    sentinel:
      db:
        limits:
          cpu: "500m"
          memory: 512Mi
        requests:
          cpu: "60m"
          memory: 256Mi
      mgmt:
        limits:
          cpu: "500m"
          memory: 150Mi
        requests:
          cpu: "60m"
          memory: 100Mi
      proxy:
        limits:
          cpu: "500m"
          memory: 150Mi
        requests:
          cpu: "60m"
          memory: 100Mi
      proxylog:
        limits:
          cpu: "500m"
          memory: 150Mi
        requests:
          cpu: "60m"
          memory: 100Mi

  lifecycleservice:
    logstash:
      limits:
        cpu: 625m
        memory: 1536Mi
      requests:
        cpu: 250m
        memory: 600Mi
    taskManager:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 1Gi
    jobManager:
      limits:
        cpu: 600m
        memory: 768Mi
      requests:
        cpu: 100m
        memory: 512Mi

  probablecause:
    replicas: 1
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 800m
      memory: 750Mi
  classifier:
    replicas: 1
    limits:
      cpu: "1"
      memory: 2048Mi
    requests:
      cpu: 400m
      memory: 750Mi
  sparkworker:
    replicas: 1
    limits:
      cpu: "1"
      memory: 1000Mi
    requests:
      cpu: 350m
      memory: 1000Mi
  sparkpipelinecomposer:
    replicas: 1
    limits:
      cpu: 250m
      memory: 768Mi
    requests:
      cpu: 250m
      memory: 600Mi

  ncodlapi:
    replicas: 1
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 512Mi
  ncodlif:
    replicas: 1
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 512Mi
  ncodlir:
    replicas: 1
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 512Mi
  ncodljobmgr:
    replicas: 1
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 512Mi
  ncodlstd:
    replicas: 1
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 512Mi
  logstash:
    replicas: 1
    limits:
      cpu: 500m
      memory: 1792Mi
    requests:
      cpu: 100m
      memory: 700Mi
  ncobackup:
    replicas: 1
    agggate:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 256Mi
    objserv:
      limits:
        cpu: 500m
        memory: 1024Mi
      requests:
        cpu: 100m
        memory: 512Mi
  ncoprimary:
    replicas: 1
    limits:
      cpu: 500m
      memory: 1024Mi  
    requests:
      cpu: 125m
      memory: 512Mi

  changeRisk:
    limits:
      cpu: 750m
      memory: 1400Mi
    requests:
      cpu: 500m
      memory: 1000Mi
  logAnomaly:
    limits:
      cpu: 500m
      memory: 2048Mi
    requests:
      cpu: 250m
      memory: 256Mi
  aiPlatformApiServer:
    limits:
      memory: 2Gi
      cpu: 200m
    requests:
      memory: 512Mi
      cpu: 100m

  nginx:
    replicas: 1

  usermgmt:
    replicas: 1

  zencore:
    replicas: 1

  zencoreapi:
    replicas: 1

  elasticsearch:
    replicas: 1
    javaOps: "-Xms512M -Xmx512M"
    elasticsearch:
      limits:
        cpu: 500m
        memory: 1536Mi
      requests:
        cpu: 250m
        memory: 1Gi
    tlsproxy:
      limits:
        cpu: 500m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 100Mi

  kafka:
    entityOperator:
      tlsSidecar:
        limits:
          cpu: 500m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 64Mi
      topicOperator:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 256Mi
      userOperator:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 256Mi
    kafka:
      replicas: 1
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 500Mi
    zookeeper:
      replicas: 1
      limits:
        cpu: 1000m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 256Mi

  flink:
    jobmanager:
      replicas: 1
      jobmanager:
        limits:
          cpu: 750m
          memory: 768Mi
        requests:
          cpu: 100m
          memory: 768Mi
      tlsproxy:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 256Mi
      heapSize: 256mb
      jvmMetaSpaceSize: 64mb
    taskmanager:
      replicas: 1
      taskmanager:
        limits:
          cpu: "1"
          memory: 1200Mi
        requests:
          cpu: 500m
          memory: 1200Mi
      heapSize: 800mb
      managedSize: 102mb
      numberOfTaskSlots: "8"

  aiopsedgeOperator:
    replicas: 1

  irflink:
    jobmanager:
      replicas: 1
      jobmanager:
        limits:
          cpu: 600m
          memory: 768Mi
        requests:
          cpu: 100m
          memory: 512Mi
      tlsproxy:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 256Mi
      processSize: 768mb
    taskmanager:
      replicas: 1
      taskmanager:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 250m
          memory: 1Gi
      processSize: 1gb

  kong:
    replicas: 1
