kind: ConfigMap
apiVersion: v1
metadata:
  name: aiops-topology-sizing
  namespace: {{.Values.spec.cp4waiops_namespace}}
  annotations:
    argocd.argoproj.io/sync-wave: "120"
data:
  asm: |
    "cassandra":
      specs:
        replicas: {{.Values.res.cassandra.replicas}}
      containers:
        "cassandra":
          resources:
            limits:
              cpu: {{.Values.res.cassandra.limits.cpu}}
              memory: {{.Values.res.cassandra.limits.memory}}
            requests:
              cpu: {{.Values.res.cassandra.requests.cpu}}
              memory: {{.Values.res.cassandra.requests.memory}}
          env:
            - name: CASSANDRA_HEAP_SIZE
              value: 600M
            - name: CASSANDRA_HEAP_NEWSIZE
              value: 150M
