---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: customize-profile-job
  annotations:
    argocd.argoproj.io/sync-wave: "130"
  namespace: {{.Values.spec.cp4waiops_namespace}}
spec:
  schedule: "*/10 * * * *"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: openshift-argocd-admin
          restartPolicy: OnFailure
          containers:
          - name: config
            image: quay.io/openshift/origin-cli:latest
            imagePullPolicy: IfNotPresent
            resources:
              requests:
                memory: "64Mi"
                cpu: "100m"
              limits:
                memory: "128Mi"
                cpu: "250m"
            command:
              - /bin/sh
              - -c
              - |

                ns="{{.Values.spec.cp4waiops_namespace}}"

                replicas=$(oc get deploy ibm-nginx -n $ns -o jsonpath="{.spec.replicas}")
                if [[ $replicas != 1 ]]; then
                  oc patch deploy ibm-nginx -n $ns --type=merge -p '{"spec": {"replicas": 1}}'
                fi

                replicas=$(oc get deploy usermgmt -n $ns -o jsonpath="{.spec.replicas}")
                if [[ $replicas != 1 ]]; then
                  oc patch deploy usermgmt -n $ns --type=merge -p '{"spec": {"replicas": 1}}'
                fi

                replicas=$(oc get deploy zen-core -n $ns -o jsonpath="{.spec.replicas}")
                if [[ $replicas != 1 ]]; then
                  oc patch deploy zen-core -n $ns --type=merge -p '{"spec": {"replicas": 1}}'
                fi

                replicas=$(oc get deploy zen-core-api -n $ns -o jsonpath="{.spec.replicas}")
                if [[ $replicas != 1 ]]; then
                  oc patch deploy zen-core-api -n $ns --type=merge -p '{"spec": {"replicas": 1}}'
                fi

                replicas=$(oc get deploy aiopsedge-operator-controller-manager -n $ns -o jsonpath="{.spec.replicas}")
                if [[ $replicas != 1 ]]; then
                  oc patch deploy aiopsedge-operator-controller-manager -n $ns --type=merge -p '{"spec": {"replicas": 1}}'
                fi
