apiVersion: orchestrator.aiops.ibm.com/v1alpha1
kind: Installation
metadata:
  name: aiops-installation
  namespace: {{.Values.spec.cp4waiops_namespace}}
  annotations:
    argocd.argoproj.io/sync-wave: "120"
spec:
  size: {{.Values.spec.size}}
  storageClass: {{.Values.spec.storageClass}}
  storageClassLargeBlock: {{.Values.spec.storageClassLargeBlock}}
  imagePullSecret: ibm-entitlement-key
  license:
    accept: true
  pakModules:
  - name: aiopsFoundation
    enabled: false
    config:
      - name: couchdb
        spec:
          couchdbcluster:
            resources:
              db:
                limits:
                  cpu: "700m"
                  memory: "768Mi"
                requests:
                  cpu: "250m"
                  memory: "768Mi"
              search:
                limits:
                  cpu: "500m"
                  memory: "250Mi"
                requests:
                  cpu: "250m"
                  memory: "250Mi"
              mgmt:
                limits:
                  cpu: "500m"
                  memory: "128Mi"
                requests:
                  cpu: "250m"
                  memory: "64Mi"
      - name: redis
        spec:
          redissentinel:
            resources:
              member:
                db:
                  limits:
                    cpu: "500m"
                    memory: 512Mi
                  requests:
                    cpu: "60m"
                    memory: 256Mi
                mgmt:
                  limits:
                    cpu: "500m"
                    memory: 150Mi
                  requests:
                    cpu: "60m"
                    memory: 100Mi
                proxy:
                  limits:
                    cpu: "500m"
                    memory: 150Mi
                  requests:
                    cpu: "60m"
                    memory: 100Mi
                proxylog:
                  limits:
                    cpu: "500m"
                    memory: 150Mi
                  requests:
                    cpu: "60m"
                    memory: 100Mi
              sentinel:
                db:
                  limits:
                    cpu: "500m"
                    memory: 512Mi
                  requests:
                    cpu: "60m"
                    memory: 256Mi
                mgmt:
                  limits:
                    cpu: "500m"
                    memory: 150Mi
                  requests:
                    cpu: "60m"
                    memory: 100Mi
                proxy:
                  limits:
                    cpu: "500m"
                    memory: 150Mi
                  requests:
                    cpu: "60m"
                    memory: 100Mi
                proxylog:
                  limits:
                    cpu: "500m"
                    memory: 150Mi
                  requests:
                    cpu: "60m"
                    memory: 100Mi
  - name: applicationManager
    config:
      - name: ir-lifecycle-operator
        spec:
          lifecycleservice:
            customSizing:
              logstash:
                resourceLimitsCPU: 625m
                resourceLimitsMemory: 1Gi
                resourceRequestsCPU: 250m
                resourceRequestsMemory: 600Mi
              taskManager:
                resourceLimitsCPU: 500m
                resourceLimitsMemory: 1Gi
                resourceRequestsCPU: 250m
                resourceRequestsMemory: 1Gi
              jobManager:
                resourceLimitsCPU: 600m
                resourceLimitsMemory: 768Mi
                resourceRequestsCPU: 100m
                resourceRequestsMemory: 512Mi
      - name: ir-ai-operator
        spec:
          aiopsanalyticsorchestrator:
            customSizing:
              deployments:
                - name: probablecause
                  replicas: 1
                  containers:
                  - name: probablecause
                    limits:
                      cpu: 1000m
                      memory: 1Gi
                    requests:
                      cpu: 800m
                      memory: 750Mi
                - name: classifier
                  replicas: 1
                  containers:
                  - name: classifier
                    limits:
                      cpu: "1"
                      memory: 2048Mi
                    requests:
                      cpu: 800m
                      memory: 750Mi
                - name: spark-worker
                  replicas: 1
                  containers:
                  - name: spark-worker
                    limits:
                      cpu: "1"
                      memory: 1000Mi
                    requests:
                      cpu: 350m
                      memory: 1000Mi
                - name: spark-pipeline-composer
                  replicas: 1
                  containers:
                  - name: spark-pipeline-composer
                    limits:
                      cpu: 250m
                      memory: 500Mi
                    requests:
                      cpu: 250m
                      memory: 500Mi
            pullSecrets:
            - ibm-entitlement-key
      - name: ir-core-operator
        spec:
          issueresolutioncore:
            customSizing:
              deployments:
                - name: ncodl-api
                  replicas: 1
                  containers:
                  - name: api
                    limits:
                      cpu: 500m
                      memory: 1024Mi
                    requests:
                      cpu: 100m
                      memory: 512Mi
                - name: ncodl-if
                  replicas: 1
                  containers:
                  - name: iducforward
                    limits:
                      cpu: 500m
                      memory: 1024Mi
                    requests:
                      cpu: 100m
                      memory: 512Mi
                - name: ncodl-ir
                  replicas: 1
                  containers:
                  - name: iducrelay
                    limits:
                      cpu: 500m
                      memory: 1024Mi
                    requests:
                      cpu: 50m
                      memory: 512Mi
                - name: ncodl-jobmgr
                  replicas: 1
                  containers:
                  - name: jobmgr
                    limits:
                      cpu: 500m
                      memory: 1024Mi
                    requests:
                      cpu: 50m
                      memory: 512Mi
                - name: ncodl-std
                  replicas: 1
                  containers:
                  - name: standard
                    limits:
                      cpu: 500m
                      memory: 1024Mi
                    requests:
                      cpu: 50m
                      memory: 512Mi
                - name: logstash
                  replicas: 1
                  containers:
                  - name: logstash
                    limits:
                      cpu: 500m
                      memory: 1400Mi
                    requests:
                      cpu: 100m
                      memory: 700Mi
              statefulSets:
                - name: ncobackup
                  replicas: 1
                  containers:
                  - name: agg-gate
                    limits:
                      cpu: 500m
                      memory: 512Mi
                    requests:
                      cpu: 50m
                      memory: 256Mi
                  - name: objserv
                    limits:
                      cpu: 500m
                      memory: 1024Mi
                    requests:
                      cpu: 100m
                      memory: 512Mi
                - name: ncoprimary
                  replicas: 1
                  containers:
                  - name: objserv
                    limits:
                      cpu: 500m
                      memory: 1024Mi  
                    requests:
                      cpu: 125m
                      memory: 512Mi
    enabled: false
  - name: aiManager
    enabled: false
