---
apiVersion: batch/v1
kind: Job
metadata:
  name: cp4waiops-patch-job
  annotations:
    argocd.argoproj.io/sync-wave: "130"
  namespace: {{.Values.spec.cp4waiops_namespace}}
spec:
  template:
    spec:
      initContainers:
      - name: wait
        image: quay.io/openshift/origin-cli:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        command:
          - /bin/sh
          - -c
          - |
            ns="{{.Values.spec.cp4waiops_namespace}}"

            until oc get aiopsanalyticsorchestrator/aiops  -n $ns -o name; do
              echo "Waiting for aiopsanalyticsorchestrator/aiops ..."
              sleep 10s
            done

            until oc get sa/aiops-topology-service-account -n $ns -o name; do
              echo "Waiting for sa/aiops-topology-service-account ..."
              sleep 10s
            done
      containers:
      - name: patch
        image: quay.io/openshift/origin-cli:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        command:
          - /bin/sh
          - -c
          - |
            set -x

            ns="{{.Values.spec.cp4waiops_namespace}}"

            oc patch aiopsanalyticsorchestrator aiops -n $ns --type=merge -p '{"spec": {"pullSecrets": ["ibm-entitlement-key"]}}'
            oc patch sa/aiops-topology-service-account -n $ns --type=merge -p '{"metadata": {"labels": {"managedByUser": "true"}}, "imagePullSecrets": [{"name": "ibm-entitlement-key"}]}'

            res=$(oc get pod -n $ns | grep aiops-topology-cassandra-auth-secret-generator | awk '{print $1}')
            if [[ -n $res ]]; then
              oc delete pod $res -n $ns
            fi

            res=$(oc get pod -n $ns | grep aiops-ir-analytics | awk '{print $1}')
            if [[ -n $res ]]; then
              oc delete pod $res -n $ns
            fi
      restartPolicy: Never
      serviceAccountName: openshift-argocd-admin
  backoffLimit: 1
