---
argocd:
  cluster: kubernetes
  namespace: argocd
  
cp4waiops:
  enabled: true
  instanceName: aiops-installation
  dockerPassword: REPLACE_IT

sampleapp:
  enabled: true
  clusterDomain: REPLACE_IT
