{{- if .Values.cp4waiops.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cp4waiops
spec:
  generators:
  {{- if .Values.argocd.allowLocalDeploy }}
  - clusters: {}
  {{- else }}
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  {{- end }}
  template:
    metadata:
      name: '{{ `{{name}}-cp4waiops` }}'
      annotations:
        argocd.argoproj.io/sync-wave: "200"
    spec:
      destination:
        namespace: cp4waiops
        server: '{{ `{{server}}` }}'
      project: default
      source:
        path: config/3.2/cp4waiops
        repoURL: https://github.com/morningspace/cp4waiops-gitops
        targetRevision: dev
        helm:
          parameters:
            - name: spec.dockerPassword
              value: '{{ .Values.cp4waiops.dockerPassword }}'
            - name: spec.installationName
              value: '{{ .Values.cp4waiops.instanceName }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
{{- end }}