apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: robot-shop-prereqs
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{ `{{name}}-robot-shop-prereq` }}'
      annotations:
        argocd.argoproj.io/sync-wave: "150"
    spec:
      destination:
        namespace: robot-shop
        server: '{{ `{{server}}` }}'
      project: default
      source:
        path: config/apps/robot-shop
        repoURL: https://github.com/morningspace/sample-app-gitops
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
