apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rook-cephs
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{ `{{name}}-rook-ceph` }}'
      annotations:
        argocd.argoproj.io/sync-wave: "100"
    spec:
      destination:
        namespace: rook-ceph
        server: '{{ `{{server}}` }}'
      project: default
      source:
        path: ceph
        repoURL: https://github.com/morningspace/cp4waiops-gitops
        targetRevision: dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
