apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: humio-loggings
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{name}}-humio-logging'
      annotations:
        argocd.argoproj.io/sync-wave: "200"
    spec:
      destination:
        namespace: humio-logging
        server: '{{server}}'
      project: default
      source:
        path: gitops-charts/humio-helm-charts
        repoURL: https://github.com/morningspace/sample-app-gitops
        targetRevision: HEAD
        helm:
          parameters:
            - name: humio-core.openshift.host
              value: TARGET_CLUSTER_DOMAIN
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
