apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: resource-locker
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{name}}-resource-locker'
    spec:
      destination:
        namespace: resource-locker-operator
        server: '{{server}}'
      project: default
      source:
        chart: resource-locker-operator
        repoURL: https://github.com/infra-team/cluster-deployments.git
        targetRevision: v1.1.3
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
