apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rook-ceph
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{cluster}}-rook-ceph'
    spec:
      destination:
        namespace: rook-ceph
        server: '{{url}}'
      project: default
      source:
        path: ceph
        repoURL: https://github.com/morningspace/cp4waiops-gitops
        targetRevision: dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
