---
apiVersion: batch/v1
kind: Job
metadata:
  name: cp4waiops-patch
  annotations:
    argocd.argoproj.io/sync-wave: "130"
  namespace: {{.Values.spec.aiManager.namespace}}
spec:
  template:
    spec:
      containers:
        - name: config
          image: quay.io/openshift/origin-cli:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "150m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          command:
            - /bin/sh
            - -c
            - |
              set -x

              while : ; do
                ai_ir=$(oc get AIOpsAnalyticsOrchestrator aiops -n {{.Values.spec.aiManager.namespace}} -o jsonpath={.kind})
                if [[ $? != 0 ]]; then
                  echo '"AIOpsAnalyticsOrchestrator" has not been created yet.'
                  sleep 10s
                else
                  break
                fi
              done

              cat <<EOF | oc apply -n {{.Values.spec.aiManager.namespace}} -f -
                apiVersion: ai.ir.aiops.ibm.com/v1beta1
                kind: AIOpsAnalyticsOrchestrator
                metadata:
                  name: aiops
                spec:
                  pullSecrets:
                  - ibm-entitlement-key
              EOF

              aiops_ir_name=$(kubectl get pod -n {{.Values.spec.aiManager.namespace}} | grep aiops-ir-analytics | awk '{print $1}')
              if [[ "${aiops_ir_name}" != "" ]]; then
                oc delete pod ${aiops_ir_name} -n {{.Values.spec.aiManager.namespace}}
              fi

      restartPolicy: Never
      serviceAccountName: openshift-argocd-admin-ai
  backoffLimit: 4