name: Release Charts

on:
  push:
    branches:
      - dev
    paths:
      - 'config/3.2/**'
      - 'config/3.3/aiManager/**'
      - 'config/3.3/eventManager/**'

  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser (CP4WAIOps 3.2)
        uses: helm/chart-releaser-action@v1.3.0
        with:
          version: v1.3.0
          charts_dir: 'config/3.2'
        env:
          CR_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: Run chart-releaser (CP4WAIOps 3.3)
        uses: helm/chart-releaser-action@v1.3.0
        with:
          version: v1.3.0
          charts_dir: 'config/3.3'
        env:
          CR_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
